"""Add columns to all tables

Revision ID: 197d91fac9d8
Revises: 75447a49d095
Create Date: 2025-04-26 10:13:22.209424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '197d91fac9d8'
down_revision: Union[str, None] = '75447a49d095'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('arguments', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('arguments', 'by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_arguments_id'), 'arguments', ['id'], unique=False)
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    op.drop_column('users', 'name')
    op.drop_index(op.f('ix_arguments_id'), table_name='arguments')
    op.alter_column('arguments', 'by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('arguments', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
