"""Add initiator column to sessions table

Revision ID: 4517a1304d67
Revises: 4e07ba5b0591
Create Date: 2025-04-27 15:10:17.289853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4517a1304d67'
down_revision: Union[str, None] = '4e07ba5b0591'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('initiator', sa.String(), nullable=True, comment="Who initiated the session. The value can be 'user' or 'ai'."))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'initiator')
    # ### end Alembic commands ###
