"""Change by column on arguments table to role

Revision ID: 53478d2f79c7
Revises: ea5b51863213
Create Date: 2025-04-26 15:43:50.494744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53478d2f79c7'
down_revision: Union[str, None] = 'ea5b51863213'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arguments', sa.Column('role', sa.String(), nullable=False))
    op.drop_column('arguments', 'by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arguments', sa.Column('by', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('arguments', 'role')
    # ### end Alembic commands ###
