"""Update models changes

Revision ID: 75447a49d095
Revises: 68293e8436c0
Create Date: 2025-04-26 10:05:51.671740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75447a49d095'
down_revision: Union[str, None] = '68293e8436c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arguments', sa.Column('by', sa.String(), nullable=True))
    op.add_column('arguments', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('arguments', 'created_at')
    op.drop_column('arguments', 'by')
    # ### end Alembic commands ###
